services:
  privacypost:
    image: registry.sccs.swarthmore.edu/cs77-s25/privacypost/privacypost:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DOMAIN: https://privacypost.sccs.swarthmore.edu/
    #env_file:
    #  - .env
    volumes:
       - privacypost-dbdata:/instance
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.routers.privacypost.entrypoints=https"
        - "traefik.http.routers.privacypost.rule=Host(`privacypost.sccs.swarthmore.edu`)"
        - "traefik.http.routers.privacypost.tls=true"
        - "traefik.http.routers.privacypost.tls.certresolver=letsEncrypt"
        - "traefik.http.services.privacypost.loadbalancer.server.port=6000"
    networks:
      - internal
      - traefik

volumes:
  privacypost-dbdata:
    name: privacypost-dbdata
    driver_opts:
      type: nfs
      o: "nfsvers=4,addr=130.58.218.26,rw,nolock,soft"
      device: ":/volumes/privacypost-dbdata"

networks:
  internal:

  traefik:
    external: true
