"""initial migration

Revision ID: 039e17885865
Revises: 
Create Date: 2025-04-19 19:06:47.965084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039e17885865'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_added')

    # ### end Alembic commands ###
